### ISSUE TITLE
It is better to use `final` when the class will not be inherited.

### ISSUE THREAD

**Issue by nov-** [mapedmediagroup/listOfArticles#1]
https://github.com/mapedmediagroup/listOfArticles/blob/8bd235f060f3b158c6dd3508da4d321231c18190/listOfArticles/listOfArticles/UI/Cells/ArticleTableViewCelTableViewCell.swift#L11

**Comment by mapedmediagroup** [comment]
fix in https://github.com/mapedmediagroup/listOfArticles/commit/501ed41b58c4d7d201467e4c6b7c41d5883d7f2d
