### ISSUE TITLE
Don't use force cast.

### ISSUE THREAD

**Issue by nov-** [mapedmediagroup/listOfArticles#4]
https://github.com/mapedmediagroup/listOfArticles/blob/8bd235f060f3b158c6dd3508da4d321231c18190/listOfArticles/listOfArticles/UI/ViewControllers/ListArticlesTableViewController.swift#L57

**Comment by mapedmediagroup** [comment]
fixed at https://github.com/mapedmediagroup/listOfArticles/commit/26701fe3cb48ba096a8a668f980e6744e0124057
