### ISSUE TITLE
Don't use force cast. What will happen if the server gives `String` instead of `Int` for this key? It will be 100% crash.

### ISSUE THREAD

**Issue by nov-** [mapedmediagroup/listOfArticles#7]
https://github.com/mapedmediagroup/listOfArticles/blob/8bd235f060f3b158c6dd3508da4d321231c18190/listOfArticles/listOfArticles/Logic/Models/ArticleModel.swift#L20

**Comment by mapedmediagroup** [comment]
fixed at https://github.com/mapedmediagroup/listOfArticles/commit/26701fe3cb48ba096a8a668f980e6744e0124057
